project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
  resources: 
    - "scripts/"

website:
  title: "Fostering Open Science in Linguistics"
  navbar:
    right:
      - tutorials.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: simplex
    css: styles.css
    toc: true
